export const sagaActions = {
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    EDIT_SUCCESS: "EDIT_SUCCESS",
    EDIT_FAILURE: "EDIT_FAILURE"
  }; 